name: NatureOfPersonality
favicon: null
layout_spectrum: 0.24488
typography_spectrum: 0.67816
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#d1dbce'
    - '#485850'
    - '#848a7b'
    - '#667165'
  brandStrength: 0.8125
  lightness: 0.47982286266051233
  saturation: 0.8406689793337137
  rhythmicContrast: 0.65511055290699
purpose: []
