name: NatureOfPersonality
favicon: null
layout_spectrum: 0.95121
typography_spectrum: 0.4951383324805647
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#8e8e8e'
    - '#3d3d3d'
    - '#df797e'
    - '#82d7bd'
  brandStrength: 0.8056383156217635
  lightness: 0.47982286266051233
  saturation: 0.8406689793337137
  rhythmicContrast: 0.65511055290699
purpose: []
